services:
  - type: web
    name: minecraft-image-processor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MAX_WORKERS
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /api/health
    healthCheckTimeout: 100
    autoDeploy: true
    domains:
      - mc-image-processer.onrender.com